### ISSUE TITLE
Input box on screen

### ISSUE THREAD

**Issue by coryhouse** [jaredreich/notie#79]
Since updating to 3.0 via npm, there's now a random input box on my screen and the notifications are now unstyled. Any tips?

I suggest using the tag and release feature of Github so the changes between major releases are clearly laid out.

Thanks!

**Comment by mactr0n** [comment]
Its because of the _main_ property in the _bower.json file_.

It is:
` "main": "notie.js",`
But after the latest changes it should be:
  "main": [
      "dist/notie.js",
      "dist/notie.css"
  ],

I will create an pull request

**Comment by mactr0n** [comment]
I fixed it an created an pull request: https://github.com/jaredreich/notie/pull/80

**Comment by jaredreich** [comment]
Sorry - #80 merged, thx folks

**Comment by razagill** [comment]
@jaredreich I think the fix is not updated on npm. I still see the inputbox on screen.

**Comment by mactr0n** [comment]
I only fixed the bower.json. The same must happen to the main property in the package.json.

**Comment by razagill** [comment]
@mactr0n I hand fixed both of them at node_modules/notie but I'm still seeing the random input box. Do I need to recompile?
